import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "LOL-INFO",
  description: "Generated by create next app",
  icons: {
    icon: "/lol_logo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="bg-gray-800 text-white p-4">
          <nav className="flex justify-around items-center w-full py-1">
            <Link href="/" className="hover:text-yellow-100">
              HOME
            </Link>
            <Link href="/champions" className="hover:text-yellow-100">
              챔피언 목록
            </Link>
            <Link href="/items" className="hover:text-yellow-100">
              아이템 목록
            </Link>
            <Link href="/rotation" className="hover:text-yellow-100">
              챔피언 로테이션
            </Link>
          </nav>
        </header>
        <main className="flex-grow flex flex-col">{children}</main>
        <footer className="bg-gray-800 text-white p-4 text-center">
        lol-info is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games and all associated properties are trademarks or registered trademarks of Riot Games, Inc.
        </footer>
      </body>
    </html>
  );
}
